[general]
import = [
  "~/.config/alacritty/tokyonight_moon.toml",
  #"~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
title = " Alacritty"
dimensions = { columns = 0, lines = 0 }
padding = { x = 12, y = 10 }
dynamic_padding = true
opacity = 1

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
bold = { family = "CommitMono Nerd Font", style = "Bold" }
italic = { family = "CommitMono Nerd Font", style = "Italic" }
bold_italic = { family = "CommitMono Nerd Font", style = "Bold Italic" }
size = 14

[terminal]
shell = { program = "/opt/homebrew/bin/zellij", args = ["options", "--default-shell", "/opt/homebrew/bin/fish"] }

